# Generated by Django 3.2.13 on 2022-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created',
            new_name='created_at',
        ),
    ]
